Repository makesmatheasy/makesmatheasy, pull requests merged in 2021-04, with the labels that each got.

#739 Added circles under Conic Sections
  appjs/index.js
  appjs/working.js
  images/circle1.png
  images/circle2.png
  images/circle3.png
  index.html
Labels: GSSOC21, Level3

#746 Made readme upto date
  README.md
  index.html
Labels: GSSOC21, Level3

#740 RECTIFIED - Factorial Calculator working
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#741 RECTIFIED - Mean, Median and Mode improper working
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#743 added some Boolean rules
  index.html
Labels: GSSOC21, Level2

#744 RECTIFIED - Permutation Combination working over floating values
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#745 Identities and Properties of Complex Numbers
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#748 Added 7's and 8's Complement
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#755 Straight Line Formulae
  appjs/index.js
  appjs/working.js
  images/anglebisec.png
  images/angleline.png
  images/perp.png
  index.html
Labels: GSSOC21, Level3

#747 RECTIFIED - Letter Character acceptance by ascending/descending
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#752 Added 15's 16's complement
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#757 Added 3-D Geometry Section
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#763 Added properties of Binomial Theorem
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#766 Bug in median calculator fixed
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#767 RECTIFIED - Time Unit Converter working
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#771 steps for calculation of Interests added
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#779 RECTIFIED - Data Unit Converter
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#790 rank calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#780 Added Application of Derivative Section
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#781 RECTIFIED - Incorrect output in 7's ands 8's complement
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#782 Invalidexpression working.
  appjs/simplecallogic.js
  index.html
Labels: GSSOC21, Level3

#783 RECTIFIED - Incorrect output in 9's ands 10's complement
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#785 RECTIFIED - Mass Unit Converter working
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#788 ENHANCED - Show steps for calculation in 1s and 2s complement
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#800 steps added under Mean Calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#806 steps added for calculation of EMI
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#816 Added option to calculate sum of AP when AP is entered
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#784 Added Coordinate Geometry Formulas and theorems
  appjs/index.js
  appjs/working.js
  images/diss.png
  index.html
Labels: GSSOC21, Level3

#787 Added Vector Algebra Section
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#808 add props of circle
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#791 Added Theorems on Differentiation
  appjs/index.js
  appjs/working.js
  images/cauchy.svg
  images/lmvt.png
  images/roll.png
  index.html
Labels: GSSOC21, Level3

#817 Solved Issue Number #538 To add Hexadecimal/Octal Converter
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#818 Solved Issue Number #732 (Bug in Geometric Mean calculator)
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#819 Statscal
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#820 added 0 condition in log
  appjs/logValue.js
Labels: GSSOC21, Level2

#821 Favourite button fixed
  index.html
Labels: GSSOC21, Level2

#822 negative values in p/b/h trigo
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#799 inverse,period of functions
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#789 ENHANCED - Show steps for calculation in 7s and 8s complement
  index.html
Labels: GSSOC21, Level3

#823 add in searchbar
  appjs/searchbar.js
Labels: GSSOC21, Level3

#836 exponent added in calculator
  index.html
Labels: GSSOC21, Level3

#827 add searchbar recommendations
  appjs/searchbar.js
Labels: GSSOC21, Level2

#826 Added calculator for multiplication of any number system
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#828 Fixed Issue Number #691 (While giving input in bcd any number which is not 0 or 1 it is show in result 0 while there should be a valid error message given)
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#829 add expo form of complex number
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#830 Added formulas under algebraic section
  index.html
Labels: GSSOC21, Level2

#831 ENHANCED - Functionality of Profit Loss Calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#832 RECTIFIED - Output formatting error in equation reduction and a few bugs
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#833 Resolved Issue Number #723 (To enhance the UI of Boolean Algebra section)
  index.html
Labels: GSSOC21, Level2

#839 Solved Issue Number #536 (To add properties of Probability)
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#840 roman convertor is modified
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#841 ENHANCED - Show steps for calculation in 15s and 16s complement
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#844 e and exp() added in calci
  appjs/simplecallogic.js
  index.html
Labels: GSSOC21, Level3

#845 RECTIFIED - Geometric Progression over letter characters
  index.html
Labels: GSSOC21, Level2

#853 add items on searchbar
  appjs/searchbar.js
Labels: GSSOC21, Level2

#854 Inverse of Matrix Calculator added(#4)
  appjs/matrixlogic.js
Labels: GSSOC21, Level3

#862 Addition of fraction bug rectified
  appjs/operations_on_fraction.js
  index.html
Labels: GSSOC21, Level2

#863 added steps for profit and loss part
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#864 Modified Trapezium working.
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#866 add conic section recommendations
  appjs/searchbar.js
Labels: GSSOC21, Level2

#870 ENHANCED - SI CI Calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#872 RECTIFIED - Incorrect output in 15's ands 16's complement
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#873 Improve upon UI of favourite formulas
  css/style.css
Labels: GSSOC21, Level2

#874 Added T-Ratios for many angles in sequence
  index.html
Labels: GSSOC21, Level2

#877 solved bug in lcm calc
  appjs/logicjavascript.js
Labels: GSSOC21, Level0

#879 Rectified-prime factor bug
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#881 added decimal-grey code converter
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#894 Num fact resolved
  css/style.css
Labels: Level1

#896 add pythagorean triplets
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#895 Solved Issue Number #726 #727 (Added left shift and right shift operator)
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#902 Cursor for favourite icon is changed
  css/bootstrap.min.css
Labels: GSSOC21, Level1

#903 Added disjoint set operation
  index.html
Labels: GSSOC21, Level2

#899 Modification in ui of boolean algebra
  css/bootstrap.min.css
  css/style.css
  index.html
Labels: GSSOC21, Level2

#904 add searchbar for equations
  appjs/searchbar.js
Labels: GSSOC21, Level2

#905 Energy calculator added
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#916 Conversion of Improper to Mixed Fraction
  appjs/operations_on_fraction.js
Labels: GSSOC21, Level2

#919 Removed duplicate operation from complex number
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#920 Moved tetrahedron option to 3D shapes
  index.html
Labels: GSSOC21, Level1

#927 CP/SP
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#908 add searchbar for basic convertors
  appjs/searchbar.js
Labels: GSSOC21, Level2

#917 Bug in Division of Fractions fixed
  appjs/operations_on_fraction.js
  index.html
Labels: GSSOC21, Level2

#928 Solved Issue Number #719 (To enhance the UI of BCD/Decimal convertor and BCD code addition)
  css/style.css
  index.html
Labels: GSSOC21, Level2

#936 Pressure Option Rectified
  index.html
Labels: GSSOC21, Level2

#941 add diff eqn
  index.html
Labels: GSSOC21, Level2

#950 Calculation part of EMI calculator fixed
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#951 Added info about P&C
  index.html
Labels: GSSOC21, Level2

#952 Added Link to Documentation Website
  README.md
Labels: GSSOC21, Level1

#956 Modified color of fav buttons and cost and selling price buttons are working fine
  index.html
Labels: GSSOC21, Level2

#953 add alert in bitwise calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#955 Added sets formulas list
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#962 Square Pyramid Calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/pyramid.gif
  index.html
Labels: GSSOC21, Level3

#964 About style
  css/style.css
  index.html
Labels: GSSOC21, Level3

#967 add searchbar recommendations for graphs
  appjs/searchbar.js
Labels: GSSOC21, Level3

#968 resized favourite button and aligned items
  index.html
Labels: GSSOC21, Level2

#972 Add properties from set operations
  index.html
Labels: GSSOC21, Level2

#954 Fixed Issue Number #929 (calculators not giving output)
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#973 Added No Favorites Message
  appjs/index.js
  css/style.css
Labels: Level2

#969 reverted back the white colour of items
  index.html
Labels: GSSOC21, Level2

#978 Matrix message
  appjs/matrixlogic.js
Labels: GSSOC21, Level2

#979 Conical Frustum calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/F1.png
  index.html
Labels: GSSOC21, Level3

#980 Division Bug Rectified
  index.html
Labels: GSSOC21, Level2

#981 SEARCHBAR FOR COMPLEX NUMBERS
  appjs/searchbar.js
Labels: GSSOC21, Level2

#985 Images added in properties of circles
  images/pr1.jpg
  images/pr10.png
  images/pr11.PNG
  images/pr12.png
  images/pr2.png
  images/pr3.png
  images/pr4.png
  images/pr5.png
  images/pr6.png
  images/pr7.png
  images/pr8.png
  images/pr9.png
  index.html
Labels: GSSOC21, Level3

#982 add searchbar recommendations for probability
  appjs/searchbar.js
Labels: GSSOC21, Level2

#983 changed the units in css files
  css/searchbar.css
  css/simplecal.css
  css/style.css
Labels: GSSOC21, Level2

#991 Cost and selling price button is working fine now
  index.html
Labels: GSSOC21, Level2

#993 add hyperbolic trigo
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#998 Enhanced UI of circle calculator in conic section as per issue #885
  index.html
Labels: GSSOC21, Level2

#1002 Bug in Geometric Mean fixed
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1003 Fixed the bug in decimal-grey converter
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1004 Fixed the bug in hollow sphere calculator in 3D shapes
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1006 Triangular pyramid calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/tripyr.png
  index.html
Labels: GSSOC21, Level3

#1008 Moved nine ten complement insside R-1 R complement
  README.md
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1007 Fixed the bug in hemisphere calculator
  index.html
Labels: GSSOC21, Level2

#1011 Added link to index.html in contact.html
  contact.html
Labels: GSSOC21, Level2

#1014 add theorem on complex nums
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1018 Searchbar
  css/style.css
Labels: GSSOC21, Level2

#974 added new shape in calcutator of 3 D shapes
  README.md
  appjs/logicjavascript.js
  images/torus.jpg
  index.html
Labels: GSSOC21, Level3

#1019 Added bot for auto-message for merged pr
  .github/workflows/Auto_message_on_pr_merge.yml
Labels: GSSOC21, Level3

#1023 add cayley theorem and diagonalization of matrix
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1024 Working of Trapezium fixed
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1025 add inverse hyperbolic trigo identities
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1029 Add nature of the roots of quadratic equation
  index.html
Labels: GSSOC21, Level2

#1033 Pentagonal Prism calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/pentprism.png
  index.html
Labels: GSSOC21, Level3

#1020 Added Tech stack badges in readme file
  README.md
Labels: GSSOC21, Level1

#1038 Bug in Improper to Mixed Fraction fixed
  appjs/operations_on_fraction.js
Labels: GSSOC21, Level2

#1039 Images added in application of derivatives
  images/decre.png
  images/incre.png
  images/inflec.png
  images/rate.jpg
  index.html
Labels: GSSOC21, Level2

#1045 add leap year
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1046 Added calculatoro for subtraction of binary no. using 1s 2s complement
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1048 Added about LCM, HCF and factors
  index.html
Labels: GSSOC21, Level2

#1050 Solved Issue Number #707 (To add a convertor to convert decimal to 2421 code )
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1053 Fixed search bar
  css/style.css
Labels: GSSOC21, Level2

#1057 not opertator added
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1042 GST Calculator Added
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1061 Coordinate Geometry calculator added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1062 Bug resolved in torus calculator
  index.html
Labels: GSSOC21, Level2

#1064 Now Decimal/Binary Converter can also work for fractional part as well
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1065 add factors of number
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1066 add more props of beta gamma functions
  index.html
Labels: GSSOC21, Level2

#1070 add searchbar recommendations for calculus section
  appjs/searchbar.js
Labels: GSSOC21, Level2

#1063 Any base converter
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1072 add searchbar recommendation for binary calculations
  appjs/searchbar.js
Labels: GSSOC21, Level2

#1081 Minors and cofactors easy code added
  appjs/matrixlogic.js
Labels: GSSOC21, Level3

#1082 Added subtraction of octal numbers using 8s complement
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1083 Message display resolved
  appjs/matrixlogic.js
  css/style.css
Labels: GSSOC21, Level2

#1091 calculator added for octagonal prism
  appjs/logicjavascript.js
  images/octprism.PNG
  index.html
Labels: GSSOC21, Level3

#1100 All favorite icons are working
  index.html
Labels: GSSOC21, Level2

#1102 Bug in add of number system
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1103 add searchbar recommendation for general maths
  appjs/searchbar.js
Labels: GSSOC21, Level2

#1104 Distance between point and line calculator added
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3
