Repository makesmatheasy/makesmatheasy, pull requests merged in 2021-03, with the labels that each got.

#30 svg-icons-added
  icons/add.svg
  icons/crossed.svg
  icons/divide.svg
  icons/minus.svg
  index.html
Labels: GSSOC'21

#32 Add-to-HomeScreen-pop-up
  index.html
  manifest.json
  service-worker.js
Labels: GSSOC'21

#36 Unit convertor
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC'21

#40 Add to homescreen pop up
  images/icon1921.png
  index.html
  manifest.json
  service-worker.js
Labels: GSSOC'21

#39 Removed the bug wrong input on button click in Calculator
  appjs/simplecallogic.js
  index.html
Labels: GSSOC'21

#50 Added an array of interesting facts instead of using XMLHttpRequest
  appjs/index.js
Labels: GSSOC21

#60 Update README.md
  README.md
Labels: GSSOC21, Level 0

#69 Responsive Calculator added
  css/simplecal.css
Labels: GSSOC21, Level 2

#81 drop icon bug fixed #38
  appjs/index.js
  icons/chevron-arrow-up.svg
  icons/down-chevron.svg
  icons/dropdown.svg
  index.html
Labels: GSSOC21, Level 1

#65 Home button bug fixed
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
Labels: GSSOC21, Level 2

#100 Added arrows on the scrollbar on the right of the navigation bar
  images/downarrow.png
  images/uparrow.png
  index.html
Labels: GSSOC21, Level 1

#105 modify README
  README.md
Labels: GSSOC21, Level 1

#109 added input fields for shapes and created a function for isosceles triangle
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level 3

#112 Responsive Font Size
  css/style.css
Labels: GSSOC21, Level0

#115 currency converter
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#114 search bar animation
  css/style.css
  index.html
Labels: GSSOC21, Level1

#122 Fixed Trigonometry Values fav button - Issue #96
  index.html
Labels: GSSOC21, Level0

#127 categories updated
  appjs/index.js
  index.html
Labels: GSSOC21, Level2

#129 Added unit conversion for time and speed in the unit converter.
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#135 Added Contributors In readme
  README.md
Labels: GSSOC21, Level0

#137 aligned about section in center
  css/style.css
Labels: GSSOC21, Level0

#138 Added trigonometric identities.
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#140 added the formula for hypotenuse
  index.html
Labels: GSSOC21, Level0

#149 Fixed false voice inputs in calculator
  appjs/speechreco.js
Labels: GSSOC21, Level3

#150 added height label to scalene triangle image
  images/scalenetriangle.png
Labels: GSSOC21, Level0

#154 simple and compound interest
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#157 line slope feature added
  appjs/logicjavascript.js
  images/line.png
  index.html
Labels: GSSOC21, Level3

#155 added product-to-sum/sum-to-product identities
  index.html
Labels: GSSOC21, Level1

#159 Added a feature of factorial and Permutation and Combination in Gener…
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#165 Added Mean Mode Median feature
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#160 Added binery and decimal converter
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#166 Backspace Button Changes
  appjs/simplecallogic.js
  index.html
Labels: GSSOC21, Level2

#168 Triple Angle Identities
  index.html
Labels: GSSOC21, Level1

#175 Added conversion of Octal to binary and viceversa
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#176 Added bitwise calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#185 Improved upon scrollbar
  css/style.css
Labels: GSSOC21, Level1

#184 resolved non functionality of circle
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#188 Intrest
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#198 Issue 186- Light mode
  css/simplecal.css
  css/style.css
  index.html
  js/materialize.min.js
Labels: GSSOC21, Level3

#213 removed duplicate interest calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level0

#222 added the height label
  images/isosceleltriangle.png
Labels: GSSOC21, Level1

#210 Added complex number calculations
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#228 Added 3-D shapes calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  images/Cuboid.png
  images/cone.jpeg
  images/cube.png
  images/cylinder.png
  images/sphere.png
  index.html
Labels: GSSOC21, Level3

#229 Prime checker & prime till n cal added (#123)
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#234 Fixed inline styling
  appjs/matrixlogic.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#237 Added warning in matrix calculator when negative or zero value is entered in dimension
  appjs/matrixlogic.js
  index.html
Labels: GSSOC21, Level2

#233 Date
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#238 Issue#179
  .DS_Store
  README.md
  appjs/index.js
  appjs/logValue.js
  appjs/searchbar.js
  index.html
Labels: GSSOC21, Level3

#249 Corrected the bug in multiplication table
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#236 Fixed the search bar
  css/style.css
  index.html
Labels: GSSOC21, Level3

#251 conflict resolved
  README.md
  appjs/index.js
  appjs/logValue.js
  appjs/searchbar.js
  index.html
Labels: GSSOC21, Level3

#252 Added the design for Favourite Panel #190
  appjs/index.js
  css/style.css
  index.html
Labels: GSSOC21, Level3

#250 Corrected the bug in mode calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#256 Added Sum of Nterms of Arithmetic Progression
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#264 Added rank calculator for single matrix in linear algebra section
  appjs/matrixlogic.js
Labels: GSSOC21, Level3

#265 Algebraic Identities added
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#271 date 2.0
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#268 feat: Add issue-labeler.yml file
  .github/workflows/issue-labeler.yml
Labels: GSSOC21, Level2

#275 Added the Ellipse area and perimeter calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#276 Date conv (duplicte are removed)
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#273 Input fields in Singular matrix displayed in matrix format
  index.html
Labels: GSSOC21, Level2

#279 Added option to calculate variance and standard deviation
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#286 add expansion of trigonometric functions
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#284 Conic Section Added
  appjs/index.js
  appjs/working.js
  css/simplecal.css
  images/Ellipse1.png
  images/Ellipse2.png
  images/Hyperbola1.png
  images/Hyperbola2.png
  images/Parabola1.png
  images/Parabola2.png
  images/Parabola3.png
  images/Parabola4.png
  index.html
Labels: GSSOC21, Level3

#291 fix the bug in changing dark mode to light mode
  css/style.css
Labels: GSSOC21, Level1

#296 angle plotter added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#294 add geometric progression
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#311 Differentiation Formulae Added
  appjs/index.js
  appjs/working.js
  css/style.css
  index.html
Labels: GSSOC21, Level3

#312 Edited code to remove p tags from the output in limits calculator
  index.html
Labels: GSSOC21, Level2

#313 add properties of matrices and determinants
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#317 Fixed Issue number #306 (Copyright section should not hover)
  index.html
Labels: GSSOC21, Level2

#326 Fixed search bar bug
  css/style.css
  index.html
Labels: GSSOC21, Level2

#337 Fixed Issue number #328 (The website link in share to whatsapp is not yet updated)
  index.html
Labels: GSSOC21, Level0

#344 Added profit loss percentage calculation
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#339 Fixed the bug in P/B/H Trigo calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#348 Add Arithmetic Progression upto n terms #334
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#350 Conditional Identities
  index.html
Labels: GSSOC21, Level3

#342 Trigonometric Ratios of some special Value
  index.html
Labels: GSSOC21, Level2

#356 Emi calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#353 Volume,CSA,TSA of 3D solids
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#341 remove duplicate identities
  index.html
Labels: GSSOC21, Level2

#369 Element overlapping side-navbar(#9)
  css/materialize.min.css
  index.html
Labels: GSSOC21, Level1

#368 Added option to calculate the sum of Infinite terms of GP
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#371 Fixed the bug in date calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#372 Added operations for a single complex number
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#357 Added general solution of trigonometric equation
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#382 Updating integration formulae both definite and indefinite integration
  index.html
Labels: GSSOC21, Level2

#385 Improved Complex calculations
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#393 Fixed the bug in interest calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#394 Prime number working
  appjs/index.js
Labels: GSSOC21, Level1

#395 Fixed the bug in EMI calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level1

#396 "SPI/CGPA Converter" Added.
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#398 Temp
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#403 add similarity and congruence of triangles
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#410 Added Statistics Formulae
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#426 GP calculator will now work for r==1 and for negative values pf r also
  appjs/logicjavascript.js
Labels: GSSOC21, Level1

#420 Added arrows to horizontal scrollbar and styled it for vertical scrollbar
  images/leftarrow.png
  images/rightarrow.png
  index.html
Labels: GSSOC21, Level1

#419 Fixed the bug in median calculator for odd sized data
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#414 Modified the output of Ascending/Descending as per issue 399
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#428 change location of volume,csa and tsa
  index.html
Labels: GSSOC21, Level1

#442 Added Sine and cosine series and identities of 3 different angles
  index.html
Labels: GSSOC21, Level1

#443 Fixes Calc issue
  appjs/working.js
Labels: GSSOC21, Level2

#449 Fixed the bug in rounding off decimal numbers
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#454 rectangular hyperbola
  index.html
Labels: GSSOC21, Level2

#456 add convergence divergence tests
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#459 Modified cal_log() as per issue 423
  appjs/logValue.js
Labels: GSSOC21, Level2

#458 Edited convertbindec() function as per issue 415
  appjs/logicjavascript.js
Labels: GSSOC21, Level1

#460 Solved Issue Number #432 (To add more Formulae in the section Definite Integration Formulae as many formulae are missing)
  index.html
Labels: GSSOC21, Level2

#461 add curve tracing
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#462 Simplified Inverse Trigo functions Added
  images/cos2inv.png
  images/cos3inv.png
  images/cosinvgraph.png
  images/sin2inv.png
  images/sin3inv.png
  images/sininvgraph.png
  images/taninv.png
  index.html
Labels: GSSOC21, Level2

#463 add coordinate system
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#467 Changed TSA of prism
  index.html
Labels: GSSOC21, Level0

#469 Important trigo results added
  index.html
Labels: GSSOC21, Level1

#466 Dividing a complex number by 0 will give invalid
  appjs/complexlogic.js
Labels: GSSOC21, Level1

#472 added some determinant property
  index.html
Labels: GSSOC21, Level2

#474 Solved Issue Number #435 (To add more Formulae in the section Indefinite Integration Formulae as many formulae are missing)
  index.html
Labels: GSSOC21, Level2

#475 Solved issue #413
  index.html
Labels: GSSOC21, Level0

#478 add vector calculus theorems
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#480 Fixed simple calculator % and added less.
  appjs/simplecallogic.js
  index.html
Labels: GSSOC21, Level2

#481 Scroll bar
  css/style.css
  index.html
Labels: GSSOC21, Level2

#490 Grey code convertor
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#493 Rectified Square calculator working over negative values
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#496 add differential equations
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#498 Implemented correct formula for mixed to improper fraction conversion
  appjs/operations_on_fraction.js
  index.html
Labels: GSSOC21, Level2

#499 Fixed working of multiplication in operations on fraction
  appjs/operations_on_fraction.js
Labels: GSSOC21, Level1

#501 Presentation Enhancement (#495)
  appjs/logicjavascript.js
Labels: GSSOC21, Level1

#502 Added vol,lsa,tsa of 4 different pyramids and prisms , also added frustum of pyramid and another 3d solid called torus(doughnut)
  index.html
Labels: GSSOC21, Level3

#492 Bcd code convertor
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#503 Tangent & Normal added
  appjs/index.js
  appjs/working.js
  images/tangent.png
  index.html
Labels: GSSOC21, Level2

#504 Solution of triangle updated
  images/Mn.png
  images/circumcircle.png
  images/incircle.png
  images/pedal.png
  index.html
Labels: GSSOC21, Level2

#506 Polar represention of complex number
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#508 probability added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#514 Solved Issue Number #400 (To add Properties of Logarithm)
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#513 Fixed bug in Logarithm Calculator
  appjs/working.js
Labels: GSSOC21, Level1

#511 added Kite under Graph and Shapes
  appjs/logicjavascript.js
  images/kite.jpg
  index.html
Labels: GSSOC21, Level3

#518 Function calling issue in Log Calculator RESOLVED
  appjs/logValue.js
  index.html
Labels: GSSOC21, Level2

#519 Added perimeter and area for triangles
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#532 Better contribution guide
  README.md
Labels: GSSOC21, Level3

#540 Corrected the formula of incircle
  index.html
Labels: GSSOC21, Level0

#544 Added joint probability
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#545 Added Domain,range and graph of inverse function
  images/arccos.png
  images/arccosec.png
  images/arccot.png
  images/arcsec.png
  images/arcsin.png
  images/arctan.png
  index.html
Labels: GSSOC21, Level2

#550 AAS property added under Congruence Properties of Triangles
  images/AASprop.png
  index.html
Labels: GSSOC21, Level1

#554 add maxima minima
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#555 Added 1's and 2's complement calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/matrixlogic.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#568 Fixed the bug in polar representation
  appjs/logicjavascript.js
Labels: GSSOC21, Level1

#566 RECTIFIED - Plot angle wrong plotting
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#561 Fixed bug in Mean calculator
  appjs/logicjavascript.js
Labels: Level2

#572 add location of roots
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#570 Fixed the bug in ascending/descending
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#575 Changed the styling of rules in SPI/CGPA calc
  index.html
Labels: GSSOC21, Level0
