Repository makesmatheasy/makesmatheasy, pull requests merged in 2021-06, with the labels that each got.

#5188 Fermat’s little theorem
  index.html
Labels: GSSOC21, Level1

#4905 steps added to Skewness calculator
  appjs/complexlogic.js
Labels: GSSOC21, Level1

#4977 Removed duplicate code for harshad num
  appjs/logicjavascript.js
Labels: GSSOC21, Level0

#4984 Added steps for pronic number
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#4986 Added delannoy number
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#5040 Triakis tetrahedron calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/triakis-tetrahedron.png
  index.html
Labels: GSSOC21, Level2

#5068 Added working steps to the Regression coefficient calculation
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level1

#5088 Added pallindrome number
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#5089 Triakis octahedron calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/triakis-octahedron.png
  index.html
Labels: GSSOC21, Level2

#5095 Added triangular bipyramid
  appjs/logicjavascript.js
  images/triangular-bipyramid.png
  index.html
Labels: GSSOC21, Level2

#5104 Added Duck Number
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#5121 enhanced the ui of F-Test calculator
  index.html
Labels: GSSOC21, Level1

#5122 Added Emrip number
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#5123 Pentakis Dodecahedron calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/pentakis-dodecahedron.png
  index.html
Labels: GSSOC21, Level2

#5137 Added magic number
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#5144 Rhombic Triacontahedron calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/rhombic-triacontahedron.png
  index.html
Labels: GSSOC21, Level2

#5156 added confidence interval theory and enhanced the ui of confidence interval calculator
  index.html
Labels: GSSOC21, Level2

#5197 Added pell number
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#5201 added exc3 to grey code converter
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#5202 added excess-3 to 2421 code converter
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#5203 Added disheptahedron
  appjs/logicjavascript.js
  images/disheptahedron.png
  index.html
Labels: GSSOC21, Level2

#5024 steps added to percentage off calculator
  appjs/complexlogic.js
Labels: GSSOC21, Level1

#5219 Github action to add lgm-soc tag for every issues and prs created
  .github/workflows/issue-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: LGMSOC21, Level2

#5224 Add transition on button hover
  css/style.css
Labels: LGMSOC21, Level1

#5230 Made the Instagram Logo More Iconic
  contact.html
  css/style.css
Labels: LGMSOC21, 🟩 Level1

#5231 NumbersFact Fixed
  index.html
Labels: LGMSOC21, 🟩 Level1

#5232 Fixed all calculators which were redirecting to Home Page
  index.html
Labels: LGMSOC21, 🟧 Level3

#5234 Update README.md of PR
  README.md
Labels: LGMSOC21, 🟩 Level1

#5236 enhanced buttons
  index.html
Labels: LGMSOC21, 🟩 Level1

#5221 fixed bug in about page
  index.html
Labels: LGMSOC21, 🟩 Level1

#5248 Added trigonometry.html in study section
  images/angle_image.jpg
  images/circle_image.jpg
  images/cos_image.jpg
  images/halfangle_image.jpg
  images/inversetrigo_image.jpg
  images/sign_image.jpg
  images/sin_image.jpg
  images/tan_image.jpg
  images/triangle_image.jpg
  images/trigo_icon.ico
  index.html
  study/trigonometry.html
Labels: LGMSOC21, 🟧 Level3

#5250 Add issue #5242 to main
  study/euclidGeometry.html
Labels: LGMSOC21, 🟩 Level1

#5251 Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#5253 Add issue #5243 to main
  index.html
Labels: LGMSOC21, 🟩 Level1

#5258 Janhvi11
  css/style.css
  images/background_image.png
Labels: LGMSOC21, 🟧 Level3

#5264 Fixed bug in p/b/h calc and added solve,reset,example buttons for tht calculator
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2

#5267 Modified the contact page
  contact.html
Labels: LGMSOC21, 🟧 Level3

#5268 Added a restart button
  index.html
Labels: LGMSOC21, 🟩 Level1

#5262 Steps added for binomial distribution pmf
  appjs/index.js
  appjs/working.js
  calculators/binomialDistributionPmf.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟥 Level4

#5271 Added Steps for distance between Excentre and Circumcentre
  appjs/working.js
  calculators/distanceBetweenExcentreAndCircumcentre.html
  calculators/excircum1.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5273 Number is clearly visible on user input for Mean Calculator Am,Gm,Hm and Sum of N terms Ap,Gp,Hp
  calculators/meanAmGmHm.html
  calculators/sumNtermsApGpHp.html
Labels: LGMSOC21, 🟩 Level1

#5275 Add issue #5261 to main
  calculators/importantSeriesSequences.html
Labels: LGMSOC21, 🟩 Level1

#5282 Organize section
  calculators/2dShapesInscribed.html
  calculators/3dGeometryCalculator.html
  calculators/3dShapesInscribed.html
  calculators/arcLengthCalculator.html
  calculators/areaOfCrescentAndLune.html
  calculators/bilinearInterpolationCalculator.html
  calculators/cartesianCoordinatesCalculator.html
  calculators/cartesianCoordinatesToPolarCoordinateCalculator.html
  calculators/complementaryAngleCalculator.html
  calculators/coordinateGeometryCalculator.html
  calculators/coterminalAngleCalculator.html
  calculators/cylindricalCoordinatesCalculator.html
  calculators/cylindricalToCartesianCoordinatesCalculator.html
  calculators/faulhaberFormula.html
  calculators/importantGraphCalculators.html
  calculators/inequalitiesOfTriangles.html
  calculators/manhattanDistanceCalculator.html
  calculators/percentageChangeInVolumeCalculator.html
  calculators/plotAngle.html
  calculators/plotBarGraph.html
  calculators/plotGraph.html
  calculators/polarCoordinatesCalculator.html
  calculators/segmentAreaCalculator.html
  calculators/sphericalCoordinatesCalculator.html
  calculators/sssTriangleAngleCalculator.html
  calculators/supplementaryAngleCalculator.html
  calculators/volumetricWeightCalculator.html
  index.html
Labels: LGMSOC21, 🟥 Level4

#5287 Interquartile range calculator added with steps
  appjs/index.js
  calculators/interQuartile.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5288 added effects to buttons on active
  css/simplecal.css
Labels: LGMSOC21, 🟩 Level1

#5291 Outlier Calculator with steps
  appjs/index.js
  calculators/outlier.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5292 Added Reset Button in Nth term of function series
  calculators/importantSeriesSequences.html
Labels: LGMSOC21, 🟩 Level1

#5298 Modified Perfect Value function as Library function
  calculators/perfectNumber.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2

#5297 Proportion Calculator added
  appjs/index.js
  calculators/proportion.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5301 Adding Mensuration Topic (#5266)
  appjs/index.js
  calculators/2Dshapes.html
  calculators/3Dshapes.html
  calculators/areaOfCrescentandLune.html
  images/circle_mens1.png
  images/cone_mens1.png
  images/cube_mens1.png
  images/cuboi_mens1.png
  images/cylinder_mens1.png
  images/equilateraltriangle_mens1.png
  images/hemisphere_mens1.png
  images/isoscelestriangle_mens1.png
  images/parallelogram_mens1.png
  images/rectangle_mens1.png
  images/rhombous_mens1.png
  images/rightangletriangle_mens1.png
  images/scalenetriangle_mens1.png
  images/sphere_mens1.png
  images/square_mens1.png
  images/trapezium_mens1.png
  index.html
  study/intro_mens.html
Labels: LGMSOC21, 🟥 Level4

#5296 speed calculator is created.
  calculators/speedCalculator.html
  index.html
Labels: LGMSOC21, 🟨 Level2

#5302 Added Particles.js in background
  css/style.css
  js/app.js
  js/particles.js
  newdesign.html
Labels: LGMSOC21, 🟨 Level2

#5308 added some badges
  README.md
Labels: LGMSOC21, 🟩 Level1

#5307 Speed Distance Time calculator improvised.
  calculators/speedCalculator.html
  calculators/speedDistanceTimeCalculator.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5311 Modified Palindrome function into Library function
  calculators/checkPalindrome.html
  calculators/happyNumber.html
  calculators/magicNumber.html
  calculators/palindromeNumber.html
  calculators/perfectNumber.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2

#5312 errors resolved in rootsOfEquation.html
  calculators/rootsOfEquation.html
Labels: LGMSOC21, 🟩 Level1

#5313 Enhanced Contact us page
  contact.html
  images/contact_us.png
Labels: LGMSOC21, 🟨 Level2

#5314 Three Star Calculator added
  appjs/index.js
  calculators/threeStar.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5316 Bugs fixed in roots of equation
  calculators/rootsOfEquation.html
Labels: LGMSOC21, 🟩 Level1

#5317 Added Topic PMI
  appjs/index.js
  index.html
  study/intro_pmi.html
  study/proof_pmi.html
  study/steps_pmi.html
Labels: LGMSOC21, 🟧 Level3

#5319 Four star calculator along with steps
  appjs/index.js
  calculators/fourStar.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5320 Probability calculator added with steps
  appjs/index.js
  calculators/probability.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5323 Fixed bug
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟩 Level1

#5324 Convolution Calculator added with steps
  appjs/index.js
  calculators/convolution.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5326 Organized Section
  calculators/abundantNumber.html
  calculators/ackermannFunction.html
  calculators/adamNumbers.html
  calculators/additiveInverse.html
  calculators/antilogCalculator.html
  calculators/bmiCalculator.html
  calculators/changeLogBaseCalculator.html
  calculators/circumRadiusAndAreaOfExternalTriangle.html
  calculators/clockAngleCalculator.html
  calculators/costAndSellingPrices.html
  calculators/crossMultiplcationCalculator.html
  calculators/deciles.html
  calculators/diamondProblemCalculator.html
  calculators/distanceBetweenIncenterAndExcenter.html
  calculators/doublingTime.html
  calculators/effectiveInterestRate.html
  calculators/errorPercentageCalculator.html
  calculators/euclidGCD.html
  calculators/expansionCalculator.html
  calculators/exponentialGrowthCalculator.html
  calculators/factorization.html
  calculators/greatestIntegerFunctionFractionalPart.html
  calculators/halfLifeCalculator.html
  calculators/heightAndDistance.html
  calculators/hyperperfectNumber.html
  calculators/interestSimpleCompound.html
  calculators/kaprekarNumber.html
  calculators/lancentArcCalculator.html
  calculators/multiplicativeInverse.html
  calculators/naturalNumbers.html
  calculators/orderOfMagnitudeCalculator.html
  calculators/pbhTrigo.html
  calculators/percentageCalculator.html
  calculators/percentageChange.html
  calculators/percentageOff.html
  calculators/percentileRankCalculator.html
  calculators/perfectSquaresCubesRange.html
  calculators/profitLossCalculations.html
  calculators/pythagoreanTriplets.html
  calculators/quartiles.html
  calculators/rankCalculator.html
  calculators/rootMeanSquare.html
  calculators/setCalculator.html
  calculators/solveForExponents.html
  calculators/sumAndDifferenceOfTrignometricFunction.html
  calculators/triangleCalculator.html
  calculators/unitRateCalculator.html
  calculators/wagstaffNumber.html
  calculators/woodallNumber.html
  calculators/workAndTimeCalculator.html
  index.html
  study/expansionOfFunctions.html
Labels: LGMSOC21, 🟥 Level4

#5328 Incircle of Triangle
  appjs/index.js
  calculators/incircleOfTriangle.html
  index.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟧 Level3

#5333 Modified Armstrong number function into Library function
  calculators/armstrongNumber.html
  calculators/checkPalindrome.html
  calculators/perfectNumber.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2
