Repository makesmatheasy/makesmatheasy, pull requests merged in 2021-05, with the labels that each got.

#1526 Added working steps for binary subtraction
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1528 labeler for proposal and feature request
  .github/issues_labeler.yml
  .github/workflows/Issue_labeler.yml
Labels: GSSOC21, Level2

#1531 Fixed Readme file
  README.md
Labels: GSSOC21, Level0

#1533 Added calculator in section circle to calculate length of chord of a circle
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1534 Solved bug in bitwise calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1537 Added rhombic dodecahedron calculator
  README.md
  appjs/logicjavascript.js
  images/rhombic-dodecahedron.png
  index.html
Labels: GSSOC21, Level3

#1538 Fixed all input cells
  css/style.css
Labels: GSSOC21, Level2

#1539 Polar representation of complex number fixed
  appjs/complexlogic.js
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1540 Added calculator for calculating Dot Product of a Vector
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1544 Hyperboloid steps added
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1525 Fixed color of heading of various topics
  css/style.css
  index.html
Labels: GSSOC21, Level2

#1553 Error Percentage Calculator added
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1568 Site made Responsive
  css/style.css
  index.html
Labels: GSSOC21, Level2

#1557 fix #1492 vector subtraction +- symbol come together
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1559 Added calculator for circle given area
  appjs/logicjavascript.js
  images/circal.PNG
  index.html
Labels: GSSOC21, Level3

#1561 Added cyclic Quadrilateral
  appjs/logicjavascript.js
  images/cycquad.PNG
  index.html
Labels: GSSOC21, Level3

#1566 Added volume and area calculator of sphere in n-dimension
  appjs/logicjavascript.js
  images/ndimsphere.png
  index.html
Labels: GSSOC21, Level3

#1570 fix fav icon bug of vector calculator
  index.html
Labels: GSSOC21, Level1

#1571 Interest, CP/SP, effective interest rate calculator positioned at correct place
  index.html
Labels: GSSOC21, Level1

#1573 Added pentagram calculator
  README.md
  appjs/logicjavascript.js
  images/pentagram.png
  index.html
Labels: GSSOC21, Level3

#1576 Added of subtraction of octal numbers
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1578 Sum of n terms of AP,GP & HP combined in a single section
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1583 factors and factor pair of given numbers
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1589 Social media icons now clickable
  index.html
Labels: GSSOC21, Level2

#1590 var added in variables
  appjs/logicjavascript.js
  appjs/matrixlogic.js
  appjs/working.js
  nerdamer/Calculus.js
Labels: GSSOC21, Level1

#1591 Added calculator for calculating Conditional Probability
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1592 add taylor maclaurin and laurent series
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1594 Updated link in Share to Whatsapp
  index.html
Labels: GSSOC21, Level0

#1585 Added calculator for Calculating Cross Product of Vector + Fixed small bug
  README.md
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1596 Supplementary Angle Calculator Added
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1601 add cauchy liouville and rouche theorem
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1614 Duplicate sections removed
  appjs/searchbar.js
  index.html
Labels: GSSOC21, Level2

#1598 Slope Calculator added
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#1603 add milne thomson method and 4 cases
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1599 Z Score Calculater Added
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1612 add angle between chord and tangent
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1617 Parabolic Arc Calculator
  appjs/index.js
  appjs/logicjavascript.js
  images/parabolic_arch.gif
  index.html
Labels: GSSOC21, Level3

#1624 Added polygon Calculator given area
  appjs/logicjavascript.js
  images/polycal.PNG
  images/polycal1.PNG
  index.html
Labels: GSSOC21, Level3

#1625 Added arch Calculator
  appjs/logicjavascript.js
  images/archcal.PNG
  index.html
Labels: GSSOC21, Level3

#1627 Favourite container slide up issue
  appjs/index.js
  css/style.css
Labels: GSSOC21, Level2

#1628 Partial right cylinder added
  appjs/index.js
  appjs/logicjavascript.js
  images/partial_cylinder.gif
  index.html
Labels: GSSOC21, Level3

#1631 Fixed all bug
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level2

#1616 add cauchy residue and methods of residue
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1684 Added calculator for calculating resultant of vectors and fixed all bugs
  appjs/complexlogic.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1629 Partial sphere calculator added
  appjs/index.js
  appjs/logicjavascript.js
  images/sphere_partial.gif
  index.html
Labels: GSSOC21, Level3

#1630 Added working steps for subtraction of hexadecimal numbers
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1632 Added working steps for subtraction of decimal numbers
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1635 fix vector sum +- and add cap on unit vectors
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1642 Added elliptic cylinder Calculator
  appjs/logicjavascript.js
  images/ellipcyc.PNG
  index.html
Labels: GSSOC21, Level3

#1659 Added truncated square pyramid Calculator
  appjs/logicjavascript.js
  images/truspyramid.PNG
  index.html
Labels: GSSOC21, Level3

#1671 Moved bin,dec,oct,hex number system converts under one tab
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1673 Coefficient Of Variation Calculator Added
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1676 add exterior angle calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1679 Triangular Prism fixed
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1681 Added Direct and Indirect Proportion calculator
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1685 calculator for scalar triple product
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1686 Bug in SEARCHBAR Recommendation for date stress and strain calclator
  appjs/searchbar.js
Labels: GSSOC21, Level2

#1688 solved bug in sum of infinite term of GP
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1689 add nth angle calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1695 Added Obelisk calculator
  appjs/logicjavascript.js
  images/obelisk.PNG
  index.html
Labels: GSSOC21, Level3

#1699 Sector of Circle fixed
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1700 Corrected output of diagonal of parallelepiped under parallelepiped calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1701 Added calculator for calculating Cramer's Rule
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1702 add existence of polygon calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1705 Bug resolved in tetrahedron
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1709 add explanation in vector dot
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1711 Weighted Mean Calculator Added
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  images/wmean.jpg
  index.html
Labels: GSSOC21, Level3

#1712 Sidebar made responsive
  index.html
Labels: GSSOC21, Level3

#1713 fix calculator buttons
  css/simplecal.css
Labels: GSSOC21, Level2

#1716 Added work and time calculator
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  css/style.css
  index.html
Labels: GSSOC21, Level3

#1715 Enhanced UI of Properties of Matrices and Determinant
  index.html
Labels: GSSOC21, Level2

#1734 Dark mode added- contact section
  contact.html
Labels: GSSOC21, Level3

#1735 Added Edge length Calculator of tetrahedron
  appjs/logicjavascript.js
  images/tetracal.png
  index.html
Labels: GSSOC21, Level3

#1741 shift of segment calculator
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level1

#1742 types of relations added
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1743 add calculator for vector triple product
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1752 Modified modal - Settings section
  index.html
Labels: GSSOC21, Level2

#1764 Added encoding in hamming code from left to right
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1765 clock angle calculator
  appjs/complexlogic.js
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1779 add charpit method to solve PDE
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1767 Trapezoid Calculator
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#1766 skewness calculator
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1789 Added hamming distance between numbers
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1788 Added reset button to Linear Algebra
  index.html
Labels: GSSOC21, Level3

#1791 Added steps of calculation in Parallelepiped calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1793 Bug fixed in subtraction of any no. sys
  index.html
Labels: GSSOC21, Level2

#1794 Added Calculator for calculating Centroid of Tetrahedron
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1796 Added reset buttons-General maths section
  index.html
Labels: GSSOC21, Level2

#1798 Made changes in documentation
  index.html
Labels: GSSOC21, Level0

#1803 Percentile Rank calculator
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1806 Added t-test calculator
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  css/style.css
  index.html
Labels: GSSOC21, Level3

#1808 Added Table under section Decimal/2421
  index.html
Labels: GSSOC21, Level1

#1809 Fixed button -> Theorem of diffrentiation
  appjs/index.js
  index.html
Labels: GSSOC21, Level2

#1810 add tridecagon calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1813 added auto_message_on_creating_issue
  .github/workflows/Auto_message_on_creatingissues.yml
Labels: GSSOC21, Level3

#1814 Added Pentahedron Calculator
  appjs/logicjavascript.js
  images/pentahedron.jpg
  index.html
Labels: GSSOC21, Level3

#1797 Added Euler's totient function
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1829 Added steps of calculation in sum of infinite term of GP
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1832 Solve for value of X
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1833 add tetradecagon calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1842 Interior Angle Added
  appjs/logicjavascript.js
  css/bootstrap.min.css
  index.html
Labels: GSSOC21, Level3

#1845 add gamma function calculator
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1848 Fixed All Bugs
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1849 Supplementary Angle, Slope, RMS, Zscore and coeff of variation calculator now displaying output
  appjs/complexlogic.js
  appjs/index.js
  index.html
Labels: GSSOC21, Level2

#1850 Any-base-to-any-base now displayed and working
  appjs/working.js
Labels: GSSOC21, Level2

#1851 Fixed wrong output of scalar triple product calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1852 Fixed Two copyright section bug
  index.html
Labels: GSSOC21, Level1

#1853 Fixed wrong output in Sum of Squares of N Natural Numbers and Sum of Cubes of N Natural Numbers
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level2

#1854 Added working steps in sum of n terms of HP
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#1900 Added more steps , rectified the formula for finding P.I.
  index.html
Labels: GSSOC21, Level2

#1906 covariance calculator added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1910 Added working steps in Sum of Squares of N Natural Numbers and Sum of Cubes of N Natural Numbers
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#1912 added hamming code calculator for right to left
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1913 Added double star polygon
  README.md
  appjs/logicjavascript.js
  images/double-star-polygon.png
  index.html
Labels: GSSOC21, Level3

#1914 Added working steps of Nth Term of HP
  appjs/complexlogic.js
Labels: GSSOC21, Level3

#1917 Added tetrahexahedron calculator
  appjs/logicjavascript.js
  images/tetrahexahedron.png
  index.html
Labels: GSSOC21, Level3

#1919 Reset buttons added - Basic convertors
  index.html
Labels: GSSOC21, Level2

#1921 Added table for excess 3 converter
  index.html
Labels: GSSOC21, Level1

#1923 Reset buttons added - Graphs and shapes
  index.html
Labels: GSSOC21, Level2

#1925 Reset buttons added - Equations section
  index.html
Labels: GSSOC21, Level2

#1926 Added calculator for calculating Vector Projection
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1927 Fixed bug in grey code/decimal converter
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1928 Corrected spelling of trigonometry
  index.html
Labels: GSSOC21, Level0

#1934 Ellipsoid working fixed
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1935 Slope of line fixed
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#1937 Bug fixed in hamming dist calc
  appjs/logicjavascript.js
Labels: GSSOC21, Level2

#1939 Added calculator for calculating Sum of N Natural Numbers
  README.md
  appjs/complexlogic.js
  appjs/index.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1940 Added steps of calculation in Sum of n terms of GP
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1941 Added working steps in scalar triple product calculator
  appjs/logicjavascript.js
Labels: GSSOC21, Level3

#1942 fixed bug in Trapezoid Calculator
  images/trapezoid2.jpg
  index.html
Labels: GSSOC21, Level2

#1943 Linear Regression Calculator Added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1953 Percentage and Ratio converter
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1929 hyperbolic trignometric ratios calculator added
  appjs/index.js
  appjs/logicjavascript.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level3

#1954 Stress & Strain section removed
  appjs/index.js
  appjs/searchbar.js
  appjs/working.js
  index.html
Labels: GSSOC21, Level2

#1959 Added calculator for Sum of first n Odd Natural Numbers
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level3

#1960 Z-test calculator added
  README.md
  appjs/index.js
  appjs/logicjavascript.js
  appjs/searchbar.js
  appjs/working.js
  css/style.css
  index.html
Labels: GSSOC21, Level3

#1963 fix typo of even odd identities
  index.html
Labels: GSSOC21, Level0

#1964 Added calculator for checking coplanar and non coplanar vectors
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1967 Reset buttons added - Binary calculations
  index.html
Labels: GSSOC21, Level2

#1969 angle of rotational symmetry
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1971 Reset buttons added - Complex Number section
  index.html
Labels: GSSOC21, Level2

#1974 add minimum side embedded calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level3

#1976 Reset buttons added - Probability Section
  index.html
Labels: GSSOC21, Level2

#1982 Reset buttons added - Statistics section
  index.html
Labels: GSSOC21, Level2

#2002 Fixed Bug in index.js (now all buttons are working)
  appjs/index.js
Labels: GSSOC21, Level1

#2000 Hero design | About page
  about.html
  icons/Math.svg
Labels: GSSOC21, Level2

#1997 Fixed Polynomial degree calculator
  appjs/logicjavascript.js
  index.html
Labels: GSSOC21, Level2

#2046 Fixed bug in Arc Length Calculator
  appjs/complexlogic.js
  index.html
Labels: GSSOC21, Level2

#2008 Enhanced the UI of lcm/hcf/factors
  css/style.css
  index.html
Labels: GSSOC21, Level2

#2009 Updated sidebar
  css/style.css
  index.html
Labels: GSSOC21, Level2
