Repository makesmatheasy/makesmatheasy, pull requests merged in 2021-07, with the labels that each got.

#5335 Circular Sector Shape Calculator added
  appdata/menudata/graphsShapes.html
  appjs/index.js
  calculators/circularSector.html
  library/logicjavascript.js
  old.html
Labels: LGMSOC21, 🟧 Level3

#5336 Add options in Basic Converters page
  appdata/menudata/basicConverters.html
Labels: LGMSOC21, 🟨 Level2

#5337 Revamped buttons and scrollbar
  about.html
Labels: LGMSOC21, 🟪 Level0

#5338 Modified Special number function into Library function
  calculators/specialNumber.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2

#5344 Change text selection background color
  index.html
Labels: LGMSOC21, 🟩 Level1

#5345 resolved issue no. #5341
  appdata/menudata/linearAlgebra.html
  calculators/solveFraction.html
Labels: LGMSOC21, 🟪 Level0

#5348 Added options in probability.html
  appdata/menudata/probability.html
Labels: LGMSOC21, 🟨 Level2

#5347 U control chart calculator added
  appdata/menudata/statistics.html
  appjs/index.js
  calculators/uControlChart.html
  library/logicjavascript.js
  old.html
Labels: LGMSOC21, 🟧 Level3

#5355 Added options in graphandshapes.html
  appdata/menudata/graphsShapes.html
Labels: LGMSOC21, 🟨 Level2

#5357 Added options in statistics.html
  appdata/menudata/statistics.html
Labels: LGMSOC21, 🟨 Level2

#5362 Modified Hyperfind function into Library function
  calculators/hyperperfectNumber.html
  library/logicjavascript.js
Labels: LGMSOC21, 🟨 Level2

#5363 Added options in conic.html
  appdata/menudata/conic.html
Labels: LGMSOC21, 🟨 Level2

#5364 Added option in complex.html
  appdata/menudata/complex.html
Labels: LGMSOC21, 🟨 Level2

#5369 Added options in calculus.html
  appdata/menudata/calculus.html
Labels: LGMSOC21, 🟨 Level2

#5368 Added options in binary.html
  appdata/menudata/binary.html
Labels: LGMSOC21, 🟨 Level2

#5371 Added options in Equation.html
  appdata/menudata/equations.html
Labels: LGMSOC21, 🟨 Level2

#5372 Added Amicable number calculator with steps
  appdata/menudata/generalMaths.html
  appjs/index.js
  calculators/amicable.html
  library/logicjavascript.js
  old.html
Labels: LGMSOC21, 🟧 Level3

#5375 bugs in calculator in general maths
  appdata/menudata/conic.html
  calculators/3dShapesInscribed.html
  library/logicjavascript.js
  old.html
Labels: LGMSOC21, 🟨 Level2

#5382 Added Options In Trigonometry Section
  appdata/menudata/trigonometry.html
Labels: LGMSOC21, 🟨 Level2

#5383 Updated Number of Calculators
  appdata/menu.html
Labels: LGMSOC21, 🟪 Level0

#5387 Resolved the issue that half life calculator keeps showing
  appdata/menudata/generalMaths.html
Labels: LGMSOC21, 🟨 Level2

#5389 Leap Year Calculator logic written.
  calculators/leapYear.html
  library/complexlogic.js
Labels: LGMSOC21, 🟨 Level2

#5392 Added section mensuration in the menu
  appdata/menu.html
  appdata/menudata/mensuration.html
Labels: LGMSOC21, 🟩 Level1

#5393 Corrected the functionality of back button
  appdata/menudata/basicConverters.html
  appdata/menudata/binary.html
  appdata/menudata/calculus.html
  appdata/menudata/complex.html
  appdata/menudata/conic.html
  appdata/menudata/equations.html
  appdata/menudata/generalMaths.html
  appdata/menudata/graphsShapes.html
  appdata/menudata/linearAlgebra.html
  appdata/menudata/probability.html
  appdata/menudata/statistics.html
  appdata/menudata/trigonometry.html
Labels: LGMSOC21, 🟩 Level1

#5396 Factorial Calculator Bug Solved
  calculators/factorial.html
  library/complexlogic.js
Labels: LGMSOC21, 🟨 Level2

#5398 Resolved Issue related to Trigonomerty calculator
  appdata/menudata/trigonometry.html
  calculators/2Dshapes.html
  calculators/3Dshapes.html
  calculators/circumRadiusAndAreaOfExternalTriangle.html
  calculators/distanceBetweenExcentreAndCircumcentre.html
  calculators/expansionCalculator.html
  calculators/heightAndDistance.html
  calculators/hyperbolicTrigonometricRatios.html
  calculators/lancentArcCalculator.html
  calculators/pbhTrigo.html
  calculators/pentopeCalculator.html
  calculators/sumAndDifferenceOfTrignometricFunction.html
  calculators/unitCircle.html
  study/expansionOfFunctions.html
  study/intro_mens.html
  study/trigonometry.html
Labels: LGMSOC21, 🟨 Level2
